Implement the smart contract with the base functionality
the-metaverse-buidlers/cryptosouvenirs pull request #3
Opened 2022-05-19 20:23 UTC by pusi2316

[Issue-9](https://trello.com/c/3jPT7M6u/9-implement-the-smart-contract-with-the-base-functionality)

2022-05-21 18:07 UTC, pusi2316 commented on blockchain/contracts/CryptoSouvenirs.sol
> +        require(os, "There was a problem during the transaction");
@barthamark @dominikfoldi ez a withdraw az nft prototypban is benne van. De itt most warningot dob egy low level call miatt. Ami szerintem "call()". Szerintetek mi legyen ezzel? Mert ahogy olvasgattam a call() használata a transfer helyett egy best practice gas optimalizáció miatt és ezeket a best practice-ket tartani kéne szerintem.

2022-05-22 17:06 UTC, barthamark requested changes

2022-05-22 17:06 UTC, barthamark commented on blockchain/test/CryptoSouvenirs.ts
> +      //console.log(this.cryptoSouvenirs);
Make sure to get rid of commented code.

2022-05-22 17:06 UTC, barthamark commented on blockchain/test/CryptoSouvenirs.ts
> +        await this.cryptoSouvenirs.connect(this.signers.admin).tokenURI(1)
You don't need the `.connect()` for reading public methods.

2022-05-22 17:06 UTC, barthamark commented on blockchain/test/CryptoSouvenirs.ts
> +    it("should mint one badge to the random guy", async function () {
Copy paste! :D

2022-05-22 17:25 UTC, pusi2316 commented on blockchain/contracts/CryptoSouvenirs.sol
> +        require(!_exists(_tokenId), "This NFT is already minted");
Yeah. I was about to do it in another issue after all. But I can do it now

2022-05-22 17:26 UTC, pusi2316 commented on blockchain/test/CryptoSouvenirs.ts
> +    it("should mint one badge to the random guy", async function () {
yes :D

2022-05-23 07:56 UTC, pusi2316 commented on blockchain/tasks/deploy/cryptosouvenirs.ts
> +  console.log(await cryptoSouvenirs.tokenURI(4));
ofc. I just thought it would be better to test with the same data

2022-05-23 09:26 UTC, pusi2316 commented on blockchain/contracts/CryptoSouvenirs.sol
> +        (bool os, ) = payable(owner()).call{value: address(this).balance}("");
I cannot find anything about suppressing warnings in solidity

2022-05-23 19:42 UTC, pusi2316 commented on blockchain/tasks/deploy/cryptosouvenirs.ts
> +  console.log(await cryptoSouvenirs.tokenURI(4));
Should I delete it or will we use this for testing?

2022-05-23 19:42 UTC, pusi2316 commented on blockchain/contracts/CryptoSouvenirs.sol
>  import "@openzeppelin/contracts/access/Ownable.sol";
I think we should address this later after further research

2022-05-23 21:45 UTC, pusi2316 commented on blockchain/contracts/CryptoSouvenirs.sol
> +error AlreadySold();
Na hát esélyesen ez nem mükődik. De én lehet most maradnék a custom errornál. @wAsnk -al azt néztük hogy ezeket az error "message"-ket majd front end-en lehet valószinűleg kiszedni.

2022-05-24 09:48 UTC, dominikfoldi commented on blockchain/contracts/CryptoSouvenirs.sol
>  import "@openzeppelin/contracts/access/Ownable.sol";
I agree.

2022-05-24 10:23 UTC, barthamark commented on blockchain/contracts/CryptoSouvenirs.sol
> +error AlreadySold();
Let's go with what you implemented so far.

2022-05-24 10:24 UTC, barthamark commented on blockchain/tasks/deploy/cryptosouvenirs.ts
> +  console.log(await cryptoSouvenirs.tokenURI(4));
I'm OK with this for now, but we'll need a different deploy script for mainnet -- if we even get there.

2022-05-24 10:28 UTC, barthamark approved these changes

2022-05-24 10:31 UTC, merged