Issue/15 init client app
the-metaverse-buidlers/cryptosouvenirs pull request #4
Opened 2022-05-21 20:33 UTC by papiliond

2022-05-23 12:54 UTC, barthamark requested changes
Please fix the linter error as well.

2022-05-23 12:54 UTC, barthamark commented on client/src/index.css
> +body {
You can delete this and the _app.css_ files as we'll implement all the custom styles in the `useStyles` hook for the `MantineProvider`.

2022-05-23 17:08 UTC, papiliond commented on client/src/index.css
> +body {
@barthamark I didn't know about this way. Let's use it 👍

2022-05-23 17:19 UTC, papiliond commented on client/src/index.css
> +body {
Fixed lint errors.

2022-05-23 18:05 UTC, barthamark commented on client/src/index.css
> +body {
@papiliond there are still linter errors for a few items.

2022-05-24 07:13 UTC, papiliond commented on client/src/index.css
> +body {
@barthamark For me both eslint and prettier gives successful output.

2022-05-24 10:13 UTC, barthamark approved these changes

2022-05-24 10:14 UTC, merged